CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
\c $POSTGRES_DATABASE
GRANT ALL ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_USER;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO $POSTGRES_USER;