CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    apiKeyHash TEXT NOT NULL,
    isAdministrator BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_api_key ON users (apiKeyHash);

CREATE TABLE IF NOT EXISTS user_api_usages (
    id INT PRIMARY KEY REFERENCES users(id),
    requestCount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS prompts (
    promptid INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    userid INT,
    title TEXT,
    prompt TEXT,
    PRIMARY KEY (promptid, userid)
);