CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    apiKeyHash TEXT NOT NULL,
    isAdministrator BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_api_key ON users (apiKeyHash);

CREATE TABLE IF NOT EXISTS user_api_usages (
    id INT PRIMARY KEY REFERENCES users(id),
    requestCount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS prompts (
    promptid INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    userid INT NOT NULL,
    title TEXT NOT NULL,
    prompt TEXT NOT NULL,
    PRIMARY KEY (promptid, userid)
);

CREATE TABLE IF NOT EXISTS activity_metrics (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    userid INT NOT NULL REFERENCES users(id),
    requestCount INT NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_metrics_method_endpoint_userid ON activity_metrics (method, endpoint, userid);