CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    apiKeyHash TEXT NOT NULL,
    isAdministrator BOOLEAN NOT NULL,
    requestCount INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_api_key ON users (apiKeyHash);